import {exportImageAsset} from './image-asset-export.js';
import {prepareRemix,prepareRemixFromParts} from './overlay-remix.js';
export async function remix(parts,ratio,seed=1){
 return (await prepareRemixFromParts(parts,ratio,seed,{maxSide:2048})).src;
}
export async function decalPicker({modal,request,esc,apply,initialCategory='popular',ratio=1.65,geometry=null,prepare=null,seed=1}){
 const $=id=>document.getElementById(id);modal('Библиотека декалей','<p>Загрузка…</p>');
 try{const catalog=await request('/api/decals');
 modal('Библиотека декалей',`<div class="two"><label class="field">Категория<select id="decalCategory"><option value="popular">Популярные</option><option value="all">Все категории</option>${catalog.map(c=>`<option value="${esc(c.id)}">${esc(c.label)}</option>`).join('')}</select></label><label class="field">Поиск декали<input id="decalSearch" placeholder="stereo, cassette, rock…"></label></div><label class="field">При выборе картинки<select id="decalOperation"><option value="place">Добавить на макет</option><option value="download">Скачать PNG в исходном размере</option><option value="copy">Копировать картинку</option></select></label><div id="decalResults" class="tiles" style="max-height:55vh;overflow:auto"></div><p id="decalStatus" role="status"></p>`);
 function results(){const cat=$('decalCategory').value,q=$('decalSearch').value.toLowerCase(),items=catalog.flatMap(c=>c.items.map(i=>({...i,category:c.id}))).filter(i=>(cat==='all'||cat==='popular'&&i.popular||cat===i.category)&&i.name.toLowerCase().includes(q));
 $('decalResults').innerHTML=items.map((i,n)=>`<button data-catalog-decal="${n}"><img loading="lazy" src="${esc(i.thumb)}" alt="${esc(i.name)}">${esc(i.name)}</button>`).join('');$('decalStatus').textContent=items.length+' изображений';
 document.querySelectorAll('[data-catalog-decal]').forEach(b=>b.onclick=async()=>{const item=items[Number(b.dataset.catalogDecal)],operation=$('decalOperation').value;b.disabled=true;$('decalStatus').textContent='Загрузка изображения…';try{const image=item.category==='overlays'&&item.id==='wild-america-remix'&&geometry?.project&&!prepare?{name:item.name,parts:[]}:await request('/api/decal?'+new URLSearchParams({category:item.category,id:item.id}));if(image.parts){const prepared=prepare?await prepare(image,seed,{geometry,request}):geometry?.project?await prepareRemix(geometry.project,geometry.surface,request,seed,{cachedParts:image.parts}):await prepareRemixFromParts(image.parts,ratio,seed);image.src=prepared.src;image.blendMode=prepared.blendMode;image.referenceSeed=prepared.seed;image.referenceRemix=prepared.kitMetadata;image.referenceAssetKey='overlay:wild-america-remix:'+prepared.seed+':'+prepared.signature;delete image.parts;delete image.kit}if(operation==='place'){await apply(image);$('modal').close()}else{const size=await exportImageAsset({...image,name:item.name},operation==='copy');$('decalStatus').textContent=(operation==='copy'?'Скопировано':'PNG подготовлен')+` · ${size.width} × ${size.height} px`;b.disabled=false}}catch(e){$('decalStatus').textContent=e.message;b.disabled=false}});
 }
 $('decalCategory').value=initialCategory;$('decalCategory').onchange=results;$('decalSearch').oninput=results;results();
 }catch(e){$('modalBody').textContent=e.message}
}
