import {svgPaint} from './color-paint.js';
import {findReferenceFlowCopySource} from './reference-flow.js';
import {renderSpineLine,spineCaseText} from './spine-text.js';
import {taperedInsets,wrapTaperedText} from './tapered-text.js';
import {imageTileSvg} from './image-effects.js';
import {cassetteOutline,cassetteWindowPath,cassetteCutPath} from './cassette-template.js';
import {jcardSlitPaths} from './jcard-slits.js';
import QRCode from 'qrcode';
import bwipjs from '@bwip-js/browser';
import {esc,dimensions,panelRects,boundText,clamp} from './model.js';
const measureCanvas=typeof document!=='undefined'?document.createElement('canvas'):null;
const measure=measureCanvas?.getContext('2d');
const codeCache=new Map();
export function codeSvg(l,{backgroundColor='#ffffff'}={}){const color=svgPaint(l.color,'',{backgroundColor}).fill;if(color==='none')return `<svg viewBox="0 0 ${l.w} ${l.h}" width="${l.w}" height="${l.h}"></svg>`;l={...l,color};const key=JSON.stringify([l.type,l.text,l.color,l.barcodeType,l.w,l.h,l.transparentCode]);if(codeCache.has(key))return codeCache.get(key);let result='';if(l.type==='qr'){const q=QRCode.create(l.text||'https://example.com',{errorCorrectionLevel:'M'}),N=q.modules.size;let path='';for(let y=0;y<N;y++)for(let x=0;x<N;x++)if(q.modules.get(y,x))path+=`M${x+4} ${y+4}h1v1h-1z`;result=`<svg viewBox="0 0 ${N+8} ${N+8}" width="${l.w}" height="${l.h}"><rect width="100%" height="100%" fill="${l.transparentCode?'none':'white'}"/><path d="${path}" fill="${esc(l.color)}"/></svg>`}else{result=bwipjs.toSVG({bcid:l.barcodeType||'ean13',text:l.text||'5901234123457',scale:3,height:12,includetext:true,padding:3,...(l.transparentCode?{}:{backgroundcolor:'FFFFFF'}),barcolor:(l.color||'#000000').slice(1),textcolor:(l.color||'#000000').slice(1)}).replace(/<svg[^>]*viewBox="([^"]+)"[^>]*>/,`<svg viewBox="$1" width="${l.w}" height="${l.h}" preserveAspectRatio="none">`)}if(codeCache.size>100)codeCache.clear();codeCache.set(key,result);return result}
function wrapLine(str,l,size,width){if(!str)return [''];const out=[];let current='';if(measure)measure.font=`${l.italic?'italic ':''}${l.fontWeight|| (l.bold?700:400)} ${size*4}px "${l.font}"`;
const fits=t=>((measure?measure.measureText(t).width/4:t.length*size*.55)+Math.max(0,t.length-1)*(l.spacing||0))*((l.fontStretch||100)/100)<=width;
for(const word of str.split(/\s+/)){const test=current?current+' '+word:word;if(fits(test)){current=test;continue}if(current)out.push(current);if(fits(word))current=word;else{current='';for(const char of word){if(!fits(current+char)&&current){out.push(current);current=''}current+=char}}}if(current)out.push(current);return out.length?out:['']}
export function textLayout(value,l){let str=l.uppercase?value.toUpperCase():value;let size=l.size;const calc=n=>l.flapTapered?wrapTaperedText(str,l,n,wrapLine):str.split('\n').flatMap(line=>wrapLine(line,l,n,l.w));let lines=calc(size);if(l.autoFit){for(let i=0;i<80&&lines.length*size*l.lineHeight>l.h&&size>.65;i++){size*=.96;lines=calc(size)}}return {lines,size,...(l.flapTapered?{insets:lines.map((_,i)=>taperedInsets(l,size,i))}:{}),overflow:lines.length*size*l.lineHeight>l.h+.1}}
function styledText(t){return t.split(/(\*\*[^*]+\*\*|\*[^*]+\*)/g).map(s=>s.startsWith('**')?`<tspan font-weight="bold">${esc(s.slice(2,-2))}</tspan>`:s.startsWith('*')?`<tspan font-style="italic">${esc(s.slice(1,-1))}</tspan>`:esc(s)).join('')}
function measureStyledWidth(text,style,size){if(measure)measure.font=`${style.italic?'italic ':''}${style.fontWeight||(style.bold?700:400)} ${size*4}px "${style.font}"`;return (measure?measure.measureText(text).width/4:text.length*size*.55)+Math.max(0,text.length-1)*(style.spacing||0)}
export function flowText(p,l,surface){if(l.referenceFlowCopySource||l.referenceFlowCopyIndex!==undefined){const original=findReferenceFlowCopySource(p,l);return original?flowText(p,original.layer,original.surface):{text:'',overflow:false}}const source=boundText(p,l,surface);if(!['lyrics','referenceContents'].includes(l.source)||l.flowIndex===undefined)return {text:source,overflow:false};const peers=(l.referenceFlow?Object.values(p.surfaces).flat().filter(x=>x.referenceFlow):p.surfaces[surface]).filter(x=>(l.referenceFlow||x.visible)&&x.source===l.source&&x.flowIndex!==undefined).sort((a,b)=>a.flowIndex-b.flowIndex);let remaining=source;for(const peer of peers){const {lines}=textLayout(remaining,{...peer,autoFit:false});const cap=Math.max(1,Math.floor(peer.h/(peer.size*peer.lineHeight)));const text=lines.slice(0,cap).join('\n');remaining=lines.slice(cap).join('\n');if(peer.id===l.id)return {text,overflow:peer===peers.at(-1)&&!!remaining}}return {text:'',overflow:false}}
export function shapePath(p,surface,bleed=0){const {w:W,h:H}=dimensions(p,surface);if(surface.startsWith('label'))return cassetteOutline(W,H,bleed);return `M${-bleed},${-bleed}H${W+bleed}V${H+bleed}H${-bleed}Z`}
export function renderSvg(p,surface,{selected='',editing=false,imageEditing=false,guides=p.settings.guides,bleed=0,blank=false,onlyLayers=false}={}){const {w:W,h:H}=dimensions(p,surface),id='s'+surface;const bg=surface==='inner'?p.settings.bgInside:surface==='labelB'?p.settings.bgB:p.settings.bg;let warnings=[],selection='';const fonts=p.fonts.map(f=>`@font-face{font-family:'${f.name.replace(/[^\w -]/g,'')}';font-weight:${Number(f.weight)||400};font-style:${f.style==='italic'?'italic':'normal'};src:url('${f.data}')}`).join('');const cutPath=surface.startsWith('label')?cassetteCutPath(p.layout,bleed):shapePath(p,surface,bleed);let defs=`<style>${fonts}</style><clipPath id="${id}-clip" clipPathUnits="userSpaceOnUse"><path d="${cutPath}" clip-rule="evenodd" fill-rule="evenodd"/></clipPath>`;if(surface.startsWith('label'))defs+=`<clipPath id="${id}-outline" clipPathUnits="userSpaceOnUse"><path d="${shapePath(p,surface,bleed)}"/></clipPath>`;
let body=blank||onlyLayers?'':`<rect x="${-bleed}" y="${-bleed}" width="${W+2*bleed}" height="${H+2*bleed}" fill="${p.settings.referenceTransparentBackground?'none':svgPaint(bg,id+'-bg').fill}"/>`;
if(!blank)for(const l of p.surfaces[surface]){if(!l.visible)continue;let content='',extra='';const lid=id+'-'+l.id.replace(/[^a-z0-9]/gi,'');if(l.type==='text'){const flow=flowText(p,l,surface);let layout=l.referenceSpine?textLayout(spineCaseText(flow.text,l,p),{...l,uppercase:false}):textLayout(flow.text,l);if(flow.overflow)warnings.push('Тексты песен не помещаются — добавьте панели или уменьшите размер');if(layout.overflow)warnings.push('Текст не помещается: '+l.name);const anchor=l.align==='center'?'middle':l.align==='right'?'end':'start',x=l.align==='center'?l.w/2:l.align==='right'?l.w:0;content=layout.lines.map((line,i)=>{const heading=line.startsWith('#'),inset=layout.insets?.[i],lineX=inset?inset.left+(l.align==='center'?(l.w-inset.left-inset.right)/2:l.align==='right'?l.w-inset.left-inset.right:0):x;return `<text x="${lineX/((l.fontStretch||100)/100)}" transform="scale(${(l.fontStretch||100)/100} 1)" y="${layout.size*.9+i*layout.size*l.lineHeight}" font-size="${layout.size}" font-family="${esc(l.font)}" fill="${svgPaint(l.color,lid,{backgroundColor:bg}).fill}" font-weight="${heading?700:l.fontWeight||(l.bold?700:400)}" font-style="${l.italic?'italic':'normal'}" font-variant="${l.smallcaps?'small-caps':'normal'}" text-anchor="${anchor}" letter-spacing="${l.spacing||0}" stroke="${esc(l.outlineColor)}" stroke-width="${l.outline||0}" paint-order="stroke" ${l.shadow?`filter="url(#${lid}-shadow)"`:''}>${renderSpineLine(line.replace(/^#{1,6}\s*/,''),layout.lines,i,l,p,layout.size,styledText,measureStyledWidth,{backgroundColor:bg,shadowId:lid+'-album-shadow'})}</text>`}).join('');if(l.shadow)defs+=`<filter id="${lid}-shadow" x="-30%" y="-30%" width="160%" height="160%"><feDropShadow dx="${l.shadow}" dy="${l.shadow}" stdDeviation="${l.shadow*.3}" flood-color="${esc(l.shadowColor)}"/></filter>`;
if(l.albumStyle?.shadow)defs+=`<filter id="${lid}-album-shadow" x="-30%" y="-30%" width="160%" height="160%"><feDropShadow dx="${l.albumStyle.shadow}" dy="${l.albumStyle.shadow}" stdDeviation="${l.albumStyle.shadow*.3}" flood-color="${esc(l.albumStyle.shadowColor||l.shadowColor)}"/></filter>`;}else if(l.type==='image'){if(l.src){content=`<g transform="translate(${l.w/2+(l.cropX||0)} ${l.h/2+(l.cropY||0)}) scale(${l.cropZoom||1}) rotate(${l.cropRotation||0}) translate(${-l.w/2} ${-l.h/2})"><image href="${esc(l.src)}" width="${l.w}" height="${l.h}" preserveAspectRatio="${l.fit==='stretch'?'none':"xMidYMid "+(l.fit==='meet'?'meet':'slice')}"/></g>`;if(l.imageTile){const tile=imageTileSvg(l,lid);defs+=tile.defs;content=tile.content}defs+=`<clipPath id="${lid}-imageclip"><rect width="${l.w}" height="${l.h}"/></clipPath>`;if(['solid','tint','gray'].includes(l.tintMode)){const col=l.tintColor||'#ffffff';const rgb=[1,3,5].map(i=>parseInt(col.slice(i,i+2),16)/255);const matrix=l.tintMode==='solid'?`0 0 0 0 ${rgb[0]} 0 0 0 0 ${rgb[1]} 0 0 0 0 ${rgb[2]} 0 0 0 1 0`:l.tintMode==='gray'?'0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0 0 0 1 0':rgb.map(v=>`${.2126*v} ${.7152*v} ${.0722*v} 0 0`).join(' ')+' 0 0 0 1 0';defs+=`<filter id="${lid}-tint" color-interpolation-filters="sRGB"><feColorMatrix type="matrix" values="${matrix}"/></filter>`;content=`<g filter="url(#${lid}-tint)">${content}</g>`}if(l.blur>0){defs+=`<filter id="${lid}-blur" x="-100%" y="-100%" width="300%" height="300%" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="${l.blur}"/></filter>`;content=`<g filter="url(#${lid}-blur)">${content}</g>`}extra=`clip-path="url(#${lid}-imageclip)"`}}else if(l.type==='shape'){if(l.shape==='ellipse')content=`<ellipse cx="${l.w/2}" cy="${l.h/2}" rx="${l.w/2}" ry="${l.h/2}" fill="${esc(l.color)}"/>`;else if(l.shape==='line')content=`<path d="M0 ${l.h/2}H${l.w}" stroke="${esc(l.color)}" stroke-width="${l.strokeWidth||.6}"/>`;else content=`<rect width="${l.w}" height="${l.h}" rx="${l.radius||0}" fill="${esc(l.color)}"/>`}else{try{content=codeSvg(l,{backgroundColor:bg})}catch(e){warnings.push('Некорректный код: '+l.name);content=`<rect width="${l.w}" height="${l.h}" fill="#ffeeee"/><text x="1" y="4" font-size="2" fill="red">Проверьте код</text>`}}
if(l.type==='image'&&l.missingReference&&!l.src){warnings.push('Загрузите файл для слоя: '+l.name);if(editing)content=`<rect width="${l.w}" height="${l.h}" fill="#f6d48a" fill-opacity=".08" stroke="#d39735" stroke-width=".3" stroke-dasharray="2 1"/><text x="2" y="5" font-size="2.5" fill="#d39735">Загрузите изображение</text>`}
const panels=!surface.startsWith('label')&&l.panelTargets?.length?panelRects(p,surface).filter((_,i)=>l.panelTargets.includes(i)):[];if(panels.length){defs+=`<clipPath id="${lid}-panels">${panels.map(r=>`<rect x="${r.x}" y="0" width="${r.w}" height="${H}"/>`).join('')}</clipPath>`;body+=`<g clip-path="url(#${lid}-panels)">`}body+=`<g ${editing?`data-layer="${esc(l.id)}" tabindex="0" role="button" aria-label="${esc(l.name)}"${imageEditing&&l.id!==selected?' pointer-events="none"':''}`:''} transform="translate(${l.x} ${l.y}) rotate(${l.rotation})" opacity="${l.opacity}" style="mix-blend-mode:${esc(l.blendMode||'normal')}" ${extra}><g transform="translate(${l.flipX?l.w:0} ${l.flipY?l.h:0}) scale(${l.flipX?-1:1} ${l.flipY?-1:1})">${content}</g>${editing?`<rect width="${l.w}" height="${l.h}" fill="transparent" stroke="none"${l.type==='text'?' pointer-events="none"':''}/>`:''}</g>`;if(panels.length)body+='</g>';
if(editing&&l.id===selected){selection+=`<g class="selection" transform="translate(${l.x} ${l.y}) rotate(${l.rotation})" fill="white" stroke="#4d9be9" stroke-width=".35"><rect width="${l.w}" height="${l.h}" fill="none" stroke-dasharray="1 .6" pointer-events="none"/><rect data-handle="resize" x="${l.w-1.4}" y="${l.h-1.4}" width="2.8" height="2.8"/><line x1="${l.w/2}" x2="${l.w/2}" y1="0" y2="-5" pointer-events="none"/><circle data-handle="rotate" cx="${l.w/2}" cy="-6" r="1.5"/></g>`}}
let guide='';if(guides||blank){if(blank||p.settings.cutGuides!==false)guide=`<path d="${shapePath(p,surface)}" fill="none" stroke="${blank?'#d000a0':'#91958a'}" stroke-width=".15"/>`;if(surface.startsWith('label')&&p.layout.hole&&(blank||p.settings.cutGuides!==false))guide+=`<path d="${cassetteWindowPath(p.layout)}" fill="none" stroke="#999" stroke-width=".15"/>`;if(!surface.startsWith('label')&&(blank||p.settings.foldGuides!==false))guide+=panelRects(p,surface).slice(1).map(r=>`<path d="M${r.x} 0V${H}" stroke="#aaa" stroke-width=".15" stroke-dasharray="1 1"/>`).join('')}
if((guides||blank)&&(blank||p.settings.cutGuides!==false))guide+=jcardSlitPaths(p,surface).map(d=>`<path data-jcard-slit="true" d="${d}" fill="none" stroke="${blank?'#d000a0':'#91958a'}" stroke-width=".15"/>`).join('');
return {svg:`<svg xmlns="http://www.w3.org/2000/svg" width="${W+bleed*2}mm" height="${H+bleed*2}mm" viewBox="${-bleed} ${-bleed} ${W+bleed*2} ${H+bleed*2}" aria-label="${surface}" role="img"><defs>${defs}</defs>${surface.startsWith('label')?`<g clip-path="url(#${id}-outline)">`:''}<g clip-path="url(#${id}-clip)">${body}</g>${surface.startsWith('label')?'</g>':''}${guide}${selection}</svg>`,warnings,w:W+bleed*2,h:H+bleed*2}}

